In [ ]:
# Day 4 Python Practice Questions:

# Practice Python Exercise:

# Function - 2 questions

# Write a function that takes a list of numbers and returns the average of all the numbers in the list.
# Write a function that takes a list of numbers and returns a new list containing only the even numbers from the original list.


# OOP - 2 questions

# Modify the 'Student' class to include a method that returns the student's details in the format "Name: [name], Age: [age], Grade: [grade]".
# Extend the 'Car' class with a method that checks if the car is more than 10 years old. If so, the method should return True; otherwise, False.

# Recursion - 2 questions

# Write a recursive function that computes the nth Fibonacci number.
# Write a recursive function that takes a list of integers and returns the sum of all even numbers in the list.


# DSA - 2 questions

# Write a function that takes a list of strings and returns the string that appears most frequently in the list. If there are multiple strings with the same highest frequency, return any one of them.
# Write a function that takes a list of integers and returns a tuple containing the smallest and largest numbers in the list.


# Pandas+Numpy - 2 questions

# Using the dataframe from Day 3, add a column 'Sports' with values 'Football', 'Basketball', 'Volleyball', 'Tennis', 'Hockey' respectively. Then, write a function that filters and returns names of students who play either 'Football' or 'Tennis'.
# Create a numpy array that represents a 5x5 matrix of random numbers between 1 and 100. Write a function that returns the sum of the diagonal elements of this matrix.

<!-- # Day 4 Python Practice Questions:

# Practice Python Exercise:

# Function - 2 questions

# Write a function that takes a list of numbers and returns the average of all the numbers in the list.
# Write a function that takes a list of numbers and returns a new list containing only the even numbers from the original list.


# OOP - 2 questions

# Modify the 'Student' class to include a method that returns the student's details in the format "Name: [name], Age: [age], Grade: [grade]".
# Extend the 'Car' class with a method that checks if the car is more than 10 years old. If so, the method should return True; otherwise, False.

# Recursion - 2 questions

# Write a recursive function that computes the nth Fibonacci number.
# Write a recursive function that takes a list of integers and returns the sum of all even numbers in the list.


# DSA - 2 questions

# Write a function that takes a list of strings and returns the string that appears most frequently in the list. If there are multiple strings with the same highest frequency, return any one of them.
# Write a function that takes a list of integers and returns a tuple containing the smallest and largest numbers in the list.


# Pandas+Numpy - 2 questions

# Using the dataframe from Day 3, add a column 'Sports' with values 'Football', 'Basketball', 'Volleyball', 'Tennis', 'Hockey' respectively. Then, write a function that filters and returns names of students who play either 'Football' or 'Tennis'.
# Create a numpy array that represents a 5x5 matrix of random numbers between 1 and 100. Write a function that returns the sum of the diagonal elements of this matrix. -->

In [2]:
# 1. Write a function that takes a list of numbers and returns the average of all the numbers in the list.

def avg(list):
    list_sum = sum(list)/len(list)
    return list_sum

print(avg([1,2,3,4,5,6,7,8,9,10]))

5.5


In [3]:
# 2. Write a function that takes a list of numbers and returns a new list containing only the even numbers from the original list.

def even_num(list):
    even_num =[]
    for i in range(len(list)):
        if list[i] % 2 == 0:
            even_num.append(list[i])
    return even_num

print(even_num([1,2,3,4,5,6,7,8,9,10]))
    

[2, 4, 6, 8, 10]


In [9]:
# 3. Modify the 'Student' class to include a method that returns the student's details in the format "Name: [name], Age: [age], Grade: [grade]".

class Student:
    def __init__(self, name, age, grade):
        self.name = name
        self.age = age
        self.grade = grade
        self.details = f"Name={self.name}, Age={self.age}, Grade={self.grade}"
        
studnet1 = Student("John", 20, "A")
print(studnet1.details)

Name=John, Age=20, Grade=A


In [16]:
# 4. Extend the 'Car' class with a method that checks if the car is more than 10 years old. If so, the method should return True; otherwise, False.

class Car:
    def __init__(self, model, year):
        self.model = model
        self.year = year
    def is_old(self):
        if 2022 - self.year > 10:
            return True
        else:
            return False

car1 = Car("Toyota", 2010)
print(car1.is_old())

True


In [18]:
# 5. Write a recursive function that computes the nth Fibonacci number.

def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(10))

55


In [28]:
# 6. Write a recursive function that takes a list of integers and returns the sum of all even numbers in the list.

def sum_even(list):
    if len(list) == 0:
        return 0
    else:
        if list[0] % 2 == 0:
            return list[0] + sum_even(list[1:])
        else:
            return sum_even(list[1:])
        
print(sum_even([1,2,3,4,5,6,7,8,9,10]))

30


In [30]:
# 7. Write a function that takes a list of strings and returns the string that appears most frequently in the list. If there are multiple strings with the same highest frequency, return any one of them.

def mf(list):
    freq = {}
    for i in list:
        if i in freq:
            freq[i] += 1
        else:
            freq[i] = 1
    max_freq = max(freq.values())
    
    fre =[]
    for key, value in freq.items():
        if value == max_freq:
            fre.append(key)
            
    return fre

mf(['a','b','c','a','b','a','a','b','b','b','c','c'])

['b']

In [31]:
# 8. Write a function that takes a list of integers and returns a tuple containing the smallest and largest numbers in the list.
def min_max(list):
    return (min(list), max(list))

print(min_max([1,2,3,4,5,6,7,8,9,10]))

(1, 10)


In [32]:
# 9. Using the dataframe from Day 3, add a column 'Sports' with values 'Football', 'Basketball', 'Volleyball', 'Tennis', 'Hockey' respectively. Then, write a function that filters and returns names of students who play either 'Football' or 'Tennis'.

import pandas as pd

data = {
    'Name': ['Tom', 'John', 'Mary', 'Mike', 'Lisa'],
    'Age': [20, 21, 22, 23, 24],
    'Grade': ['A', 'B', 'C', 'D', 'E']
}

df = pd.DataFrame(data)
df['Sports'] = ['Football', 'Basketball', 'Volleyball', 'Tennis', 'Hockey']

def filter_sports(df):
    return df[(df['Sports'] == 'Football') | (df['Sports'] == 'Tennis')]

print(filter_sports(df))


   Name  Age Grade    Sports
0   Tom   20     A  Football
3  Mike   23     D    Tennis


In [41]:
# 10. Create a numpy array that represents a 5x5 matrix of random numbers between 1 and 100. Write a function that returns the sum of the diagonal elements of this matrix.

import numpy as np

matrix = np.random.randint(1, 100, (5,5))
print(matrix)

def sum_diagonal(matrix):
    # print(np.trace(matrix))
    return np.trace(matrix)

print(sum_diagonal(matrix))

[[28 94  4 50 63]
 [13 87  5  8 26]
 [90 12 78 21 34]
 [48 83 69 82 49]
 [ 8 16 82 63 76]]
351
