In [ ]:
# Practice Python Exercise:

# Function - 2 qns
# 1. Write a function that takes a list of numbers and returns the sum of all the numbers in the list.
# 2. Write a function that takes a list of numbers and returns the largest number in the list.

#OOPs - 2 qns
# 1. Create a class called 'Student' with attributes name, age, and grade. Create a method that returns the student's name.
# 2. Create a class called 'Car' with attributes make, model, and year. Create a method that returns the make, model, and year of the car.

# Recursion - 2 qns
# 1. Write a recursive function that takes an integer and computes the factorial of that integer.
# 2. Write a recursive function that takes an integer and returns the sum of all the numbers from 0 to that integer.

#DSA - 2 qns
# 1. Write a function that takes a list of numbers and returns the largest number in the list.
# 2. Write a function that takes a list of numbers and returns the sum of all the numbers in the list.

#Pandas+Numpy - 2 qns
# 1. Create a pandas dataframe with the following data:
#    Name Age Grade
#    John 12  A
#    Jane 13  B
#    Jack 14  C
#    Jill 15  A
# 2. Create a numpy array with the following data:
#    1 2 3 4 5
#    6 7 8 9 10
#    11 12 13 14 15
#    16 17 18 19 20
#    21 22 23 24 25

#
#

In [1]:
# Q1. Write a function that takes a list of numbers and returns the sum of all the numbers in the list.
def add(list):
    return sum(list)
print(add([1,2,3,4,5]))

15


In [2]:
# Q2. Write a function that takes a list of numbers and returns the largest number in the list.
def large(list):
    list.sort()
    return list[-1]
print(large([1,2,3,4,5]))

5


In [6]:
#3. Create a class called 'Student' with attributes name, age, and grade. Create a method that returns the student's name.
class Student:
    def __init__(self, name, age, grade ):
        self.name = name
        self.age = age
        self.grade = grade
    def get_name(self):
        return self.name
    
    student1 = Student('John', 12, 'A')
    y =student1.get_name()
    print(y)

John


In [10]:
#4. Create a class called 'Car' with attributes make, model, and year. Create a method that returns the make, model, and year of the car.

class Car:
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self.year = year
        
    def car_make(self):
        return self.make
    def car_model(self):
        return self.model
    def car_year(self):
        return self.year
    
car1 = Car('Toyota','Camry',2021)
print(car1.car_make())
print(car1.car_model())
print(car1.car_year())

Toyota
Camry
2021


In [12]:
# Q5. Write a recursive function that takes an integer and computes the factorial of that integer.
def fact(n):
    if n ==0 or n==1:
        return 1
    else:
        return n*fact(n-1)
    
print(fact(5))

120


In [13]:
# Q6. Write a recursive function that takes an integer and returns the sum of all the numbers from 0 to that integer.
def sum_n(n):
    if n == 1:
        return 1
    else:
        return n + sum_n(n-1)
    
print(sum_n(5))

15


In [29]:
# Q7. Write a function that takes a list of numbers and returns the largest number in the list.
def large(list):
    n = len(list)
    # print(n)
    max = list[0]
    for i in range(1,n):
        if list[i] > max:
            print(list[i])
            max = list[i]
        else:
            max = max
    return max
print(large([1,1,2,2,1,4,6,5]))

2
4
6
6


In [30]:
# Q8. Write a function that takes a list of numbers and returns the sum of all the numbers in the list.
def sumof(list):
    l = len(list)
    sum = list[0]
    for i in range(1,l):
        sum = sum + list[i]
    return sum 
print(sumof([1,2,3,4,5]))

15


In [31]:
# Q9. Create a pandas dataframe with the following data:
#    Name Age Grade
#    John 12  A
#    Jane 13  B
#    Jack 14  C
#    Jill 15  A

import pandas as pd 
data = {'Name':['John','Jane','Jack','Jill'],
        'Age':[12,13,14,15],
        'Grade':['A','B','C','A']}
df = pd.DataFrame(data)
print(df)

   Name  Age Grade
0  John   12     A
1  Jane   13     B
2  Jack   14     C
3  Jill   15     A


In [32]:
# Q10. Create a numpy array with the following data:
#    1 2 3 4 5
#    6 7 8 9 10
#    11 12 13 14 15
#    16 17 18 19 20
#    21 22 23 24 25

import numpy as np
data = [[1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20],
        [21,22,23,24,25]]
arr = np.array(data)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
