In [1]:
# # Day 5 Python Practice Questions:
# # Practice Python Exercise:
# # Function - 2 questions
# # Write a function that takes a list of integers and returns the smallest difference between any two numbers in the list.
# # Write a function that takes a string and returns the most frequent character in the string. If there is a tie, return any of the most frequent characters.
# # OOP - 2 questions
# # Modify the 'Employee' class to include a method that increments the employee's salary by a given percentage. The method should return the new salary.
# # Create a 'Rectangle' class with methods to calculate the area and perimeter. Include checks to ensure that the lengths and widths provided are positive numbers.
# # Recursion - 2 questions
# # Write a recursive function that calculates the greatest common divisor (GCD) of two numbers.
# # Write a recursive function that reverses a string.
# # DSA - 2 questions
# # Write a function that takes a list of integers and sorts them using a selection sort algorithm.
# # Implement a function to perform binary search on a sorted list of integers to find a specific value. If the value is found, return its index; otherwise, return -1.
# # Pandas+Numpy - 2 questions
# # Using a given DataFrame, replace all NaN values with the mean of their respective columns, then return a DataFrame that contains only columns where the mean value is greater than 50.
# # Create a numpy array that represents a 5x5 matrix with values ranging from 1 to 25. Write a function that calculates and returns the sum of the elements above the main diagonal.

In [8]:
# # Function - 2 questions
# # Write a function that takes a list of integers and returns the smallest difference between any two numbers in the list.

def sm_dif(list):
    list.sort()
    min_dif = list[1] - list[0]
    for i in range(1, len(list)-1):
        if list[i+1] - list[i] < min_dif:
            min_dif = list[i+1] - list[i]
            return min_dif
        return min_dif

print(sm_dif([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

1


In [13]:
# # Write a function that takes a string and returns the most frequent character in the string. If there is a tie, return any of the most frequent characters.

def freq(string):
    freq = {}
    for char in string:
        if char in freq:
            freq[char] += 1
        else:
            freq[char] = 1
    max_freq = max(freq.values())
    print(max_freq)
    most_freq  =[]
    for key, value in freq.items():
        if value == max_freq:
            most_freq.append(key)
    return most_freq

print(freq("hello"))

2
['l']


In [16]:
# # OOP - 2 questions
# # Modify the 'Employee' class to include a method that increments the employee's salary by a given percentage. The method should return the new salary.

class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary
    def inc_salary(self,percentage):
        self.salary = self.salary +(self.salary*percentage/100)
        return self.salary
    
emp = Employee("Shyam", 50000)
print(emp.inc_salary(10))


55000.0


In [17]:
# # Create a 'Rectangle' class with methods to calculate the area and perimeter. Include checks to ensure that the lengths and widths provided are positive numbers.

class Rectangle:
    def __init__(self, length, width):
        if length <= 0 or width <= 0:
            print("Length and width should be positive numbers")
        else:
            self.length = length
            self.width = width
    def area(self):
        return self.length * self.width
    def perimeter(self):
        return 2*(self.length + self.width)
    
rect = Rectangle(5, 10)
print(rect.area())
print(rect.perimeter())


50
30


In [18]:
# # Recursion - 2 questions
# # Write a recursive function that calculates the greatest common divisor (GCD) of two numbers.

def gcd(a, b):
    if b == 0:
        return a
    else:
        return gcd(b, a%b) 
    
print(gcd(12, 15))

3


In [21]:
# # Write a recursive function that reverses a string.

def reverse(string):
    if len(string) == 0:
        return string
    else:
        return reverse(string[1:]) + string[0]
    
print(reverse("hello"))

olleh


In [23]:
# # DSA - 2 questions
# # Write a function that takes a list of integers and sorts them using a selection sort algorithm.

def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_index =i
        for j in range(i+1, n):
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]
    return arr

selection_sort([5, 3, 8, 6, 7, 2])

[2, 3, 5, 6, 7, 8]

In [26]:
def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_index = i
        for j in range(i+1, n):
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]
        print(f'After iteration {i+1}: {arr}')  # print array after each iteration
    return arr

selection_sort([5, 3, 8, 6, 7, 2])

After iteration 1: [2, 3, 8, 6, 7, 5]
After iteration 2: [2, 3, 8, 6, 7, 5]
After iteration 3: [2, 3, 5, 6, 7, 8]
After iteration 4: [2, 3, 5, 6, 7, 8]
After iteration 5: [2, 3, 5, 6, 7, 8]
After iteration 6: [2, 3, 5, 6, 7, 8]


[2, 3, 5, 6, 7, 8]

In [27]:
# # # Implement a function to perform binary search on a sorted list of integers to find a specific value. If the value is found, return its index; otherwise, return -1.

# def binary_search(arr, target):
#     left, right = 0, len(arr)-1
#     while left <= right:
#         mid = (left + right)//2
#         if arr[mid] == target:
#             return mid
#         elif arr[mid] < target:
#             left = mid + 1
#         else:
#             right = mid - 1
#     return -1

# binary_search([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], 10)

4

In [36]:
# # Pandas+Numpy - 2 questions
# # Using a given DataFrame, replace all NaN values with the mean of their respective columns, then return a DataFrame that contains only columns where the mean value is greater than 50.

import pandas as pd
import numpy as np

data = {'A': [10, 20, np.nan, 40, 50],
        'B': [5, np.nan, 15, 20, 25],
        'C': [np.nan, 10, 20, 30, 40]}
df = pd.DataFrame(data)
print(df)

df.fillna(df.mean(), inplace=True)
print(df)

df = df.loc[:, df.mean() > 2]
print(df)


      A     B     C
0  10.0   5.0   NaN
1  20.0   NaN  10.0
2   NaN  15.0  20.0
3  40.0  20.0  30.0
4  50.0  25.0  40.0
      A      B     C
0  10.0   5.00  25.0
1  20.0  16.25  10.0
2  30.0  15.00  20.0
3  40.0  20.00  30.0
4  50.0  25.00  40.0
      A      B     C
0  10.0   5.00  25.0
1  20.0  16.25  10.0
2  30.0  15.00  20.0
3  40.0  20.00  30.0
4  50.0  25.00  40.0


In [37]:
# # Create a numpy array that represents a 5x5 matrix with values ranging from 1 to 25. Write a function that calculates and returns the sum of the elements above the main diagonal.

import numpy as np

arr = np.arange(1, 26).reshape(5, 5)
print(arr)

def sum_above_diagonal(arr):
    sum = 0
    for i in range(len(arr)):
        for j in range(i+1, len(arr)):
            sum += arr[i, j]
    return sum

print(sum_above_diagonal(arr))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
90
