In [ ]:
# Numpy and Pandas from basics to advanced

# Numpy
# Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

# Pandas
# Pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series.

# Numpy and Pandas are the most popular libraries for data manipulation and analysis in Python.



In [ ]:
# Numpy
# Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
# Contents of Numpy
# 1. Introduction to Numpy
# 2. Numpy Array
# 3. Numpy Array Operations
# 4. Numpy Array Slicing
# 5. Numpy Array Iteration
# 6. Numpy Array Join
# 7. Numpy Array Split
# 8. Numpy Array Search
# 9. Numpy Array Sort
# 10. Numpy Array Filter
# 11. Numpy Random
# 12. Numpy Math Functions
# 13. Numpy Statistics
# 14. Numpy Constants
# 15. Numpy Datatypes
# 16. Numpy Copy vs View
# 17. Numpy Matrix Library
# 18. Numpy Linear Algebra
# 19. Numpy Polynomial
# 20. Numpy String Functions
# 21. Numpy DateTime
# 22. Numpy IO
# 23. Numpy Images
# 24. Numpy Applications
# 25. Numpy Quiz
# 26. Numpy Exercises
# 27. Numpy Examples

# Pandas
# Pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series.
# Contents of Pandas
# 1. Introduction to Pandas
# 2. Pandas Series
# 3. Pandas DataFrame
# 4. Pandas Indexing
# 5. Pandas GroupBy
# 6. Pandas Missing Data
# 7. Pandas Concatenation
# 8. Pandas Merging
# 9. Pandas Join
# 10. Pandas Iteration
# 11. Pandas Sorting
# 12. Pandas Aggregating
# 13. Pandas Cleaning
# 14. Pandas Input and Output
# 15. Pandas Options and Settings
# 16. Pandas Style
# 17. Pandas Reindexing
# 18. Pandas Date Functionality
# 19. Pandas TimeDelta
# 20. Pandas Categorical Data
# 21. Pandas Visualization
# 22. Pandas Time Series
# 23. Pandas Time Period
# 24. Pandas Window Functions
# 25. Pandas Resampling
# 26. Pandas Scaling
# 27. Pandas Serialization
# 28. Pandas Getting Data In/Out
# 29. Pandas Comparison with SQL
# 30. Pandas Examples
# 31. Pandas Quiz

# Numpy and Pandas are the most popular libraries for data manipulation and analysis in Python.



In [1]:
# 1. Introduction to Numpy
# Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.


# 2. Numpy Array
# Numpy Array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.
# We can initialize numpy arrays from nested Python lists and access elements using square brackets.

# Example
# Create a NumPy array from a list
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
# Output: [1 2 3 4 5]

[1 2 3 4 5]


In [2]:
# 3. Numpy Array Operations
# Numpy Array Operations include basic operations like addition, subtraction, multiplication, and division. We can perform these operations only on arrays of the same shape.

# Example
# Perform basic operations on NumPy arrays
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
# Output:
# [ 7  9 11 13 15]
# [-5 -5 -5 -5 -5]
# [ 6 14 24 36 50]
# [0.16666667 0.28571429 0.375 0.44444444 0.5]


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [6]:
# 4. Numpy Array Slicing
# Numpy Array Slicing is the process of extracting a subset of elements from an array. We can slice arrays using the colon (:) operator.

# Example
# Slice NumPy arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1,2,4,5,5])
arr3 = arr+arr2
print(arr3)
print(arr[1:4])
# Output: [2 3 4]

list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
list3 = list1 + list2
print(list3)
print(list1[1:4])
# Output: [2, 3, 4]

print(type(arr[1:4]))
print(type(list1[1:4]))


[ 2  4  7  9 10]
[2 3 4]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 3, 4]
<class 'numpy.ndarray'>
<class 'list'>


In [7]:
# 5. Numpy Array Iteration
# Numpy Array Iteration is the process of accessing each element in an array. We can use loops to iterate over NumPy arrays.

# Example
# Iterate over NumPy arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
for x in arr:
    print(type(print(x)))
# Output:
# 1
# 2
# 3
# 4
# 5


1
<class 'NoneType'>
2
<class 'NoneType'>
3
<class 'NoneType'>
4
<class 'NoneType'>
5
<class 'NoneType'>


In [17]:
# 6. Numpy Array Join
# Numpy Array Join is the process of combining two or more arrays into a single array. We can use the concatenate() function to join arrays.

# Example
# Join NumPy arrays
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

list1 = [1, 2, 3]
list2 = [2, 5, 6]
list3 = list1 + list2
print(list3)
list4 = list1.append(list2)
print(list4)
arr3 = np.concatenate((arr1, arr2))
arr4 = np.sum((arr1, arr2))
print(arr3)
print(arr4)
# Output: [1 2 3 4 5 6]

[1, 2, 3, 2, 5, 6]
None
[1 2 3 4 5 6]
21


In [18]:
# 7. Numpy Array Split
# Numpy Array Split is the process of dividing an array into multiple sub-arrays. We can use the split() function to split arrays.

# Example
# Split NumPy arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.split(arr, 3)
print(newarr)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]



[array([1, 2]), array([3, 4]), array([5, 6])]
